#!/usr/bin/env node

// Simple script for generating JSON Web Token which can be then use for
// debugging feeds REST API.
// After running this script the token is printed to console.
// Then can be used with CURL for instance: curl -H "Authorization: Bearer <ACCESS_TOKEN>"

const Pusher = require('pusher-platform-node');
const DEFAULT_TOKEN_LEEWAY = Pusher.DEFAULT_TOKEN_LEEWAY;
const PusherInstance = Pusher.Instance;

const requiredArgs = ['instanceId', 'key', 'feedId'];
const args = {};

for (let i=0; i<requiredArgs.length; i++) {
    let argumentName = requiredArgs[i];

    if (!process.argv[i+2]) {
        throw new TypeError(`Please supply ${argumentName} as ${i+1} argument.`);
    }
    
    args[argumentName] = process.argv[i+2];
}

const { instanceId, key, feedId } = args;

const getUrl = () => {
    const parsedInstanceId = instanceId.split(':').pop();

    return `https://us1.pusherplatform.io/services/feeds/v1/${parsedInstanceId}/feeds/${feedId}/items`;
};

const pusherInstance = new PusherInstance({
    instanceId,
    key,
    host: '',
    serviceVersion: 'v1',
    serviceName: 'feeds'
});

const { token } = pusherInstance.generateAccessToken({
    serviceClaims: {
        feeds: {
            permission: {
                path: '*',
                action: '*'
            }
        }
    }
});

const curlTemplate = () => (
    `curl -H "Authorization: Bearer ${token}" \ ${getUrl()}`
);

console.log(curlTemplate());
